---
title: "Project1_103"
output: pdf_document
date: "2024-07-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## Import and summarize data


```{r}
genes <- read.csv('/Users/isabellabaldacci/Desktop/QBS103/Project/QBS103_GSE157103_genes.csv', sep = ',', header = TRUE)
metadata <- read.csv('/Users/isabellabaldacci/Desktop/QBS103/Project/QBS103_GSE157103_series_matrix.csv', header = TRUE)
dim(genes)
```


```{r}
## cleaning up metadata
metadata_clean <- dplyr::select(metadata, -c("X.Sample_submission_date","channel_count","status","last_update_date","type","channel_count","source_name_ch1","organism_ch1","apacheii","ferritin.ng.ml.","ddimer.mg.l_feu.","procalcitonin.ng.ml..","lactate.mmol.l.","fibrinogen","sofa"))
head(metadata_clean)

```
```{r}
#transposing the genes x samples matrix to samples x genes
rownames(genes) <- genes$X #assigning row names
head(genes)
genes_t <- as.data.frame(t(dplyr::select(genes, -c('X')))) #transpose as a dataframe
head(genes_t)
genes_t$participant_id <- rownames(genes_t)
head(genes_t)#assigning participant id column for later joining
which(genes_t$participant_id == "COVID_06_.y_male_NonICU") #finding column with mismatch to metadata
genes_t$participant_id[6] <- "COVID_06_:y_male_NonICU" #reassinging value to match metadata

```

```{r}
#combining the samples x genes matrix to the metadata
all_data <- dplyr::inner_join(genes_t, metadata_clean, by = 'participant_id')
head(all_data)
dim(all_data) #should be 126 x 111 (100 genes, 11 cols of metadata for all 126 samples)
```
```{r}
ggplot(data = all_data, aes(A1BG)) +
  geom_histogram()
```
```{r}

```



